CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    salt TEXT NOT NULL,
    hash TEXT NOT NULL,
    iterations INTEGER NOT NULL DEFAULT 200000 CHECK (iterations > 0),
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin')),
    created DOUBLE PRECISION NOT NULL,
    changed DOUBLE PRECISION,
    session_version INTEGER NOT NULL DEFAULT 1,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deactivated_at DOUBLE PRECISION
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deactivated_at DOUBLE PRECISION;
CREATE TABLE IF NOT EXISTS accounts (
    owner_id TEXT PRIMARY KEY REFERENCES users(id),
    plan TEXT NOT NULL DEFAULT 'free',
    credits INTEGER NOT NULL DEFAULT 0 CHECK (credits >= 0),
    created DOUBLE PRECISION NOT NULL,
    ip_hash TEXT, fp_hash TEXT, note TEXT,
    blocked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES users(id),
    ts DOUBLE PRECISION NOT NULL,
    plan TEXT NOT NULL, kind TEXT NOT NULL,
    listing_key TEXT, job_id TEXT UNIQUE,
    ip_hash TEXT, fp_hash TEXT,
    credits INTEGER NOT NULL DEFAULT 1,
    debited BOOLEAN NOT NULL DEFAULT FALSE,
    refunded_at DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS ix_usage_owner ON usage(owner_id);
CREATE INDEX IF NOT EXISTS ix_usage_ip ON usage(ip_hash);
CREATE INDEX IF NOT EXISTS ix_usage_fp ON usage(fp_hash);
CREATE INDEX IF NOT EXISTS ix_usage_ts ON usage(ts);
CREATE TABLE IF NOT EXISTS outreach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES users(id),
    ts DOUBLE PRECISION NOT NULL,
    channel TEXT, name TEXT, url TEXT, city TEXT, message TEXT,
    status TEXT NOT NULL DEFAULT 'queued', note TEXT, sent_at DOUBLE PRECISION, meta TEXT
);
CREATE INDEX IF NOT EXISTS ix_outreach_owner ON outreach(owner_id);
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES users(id),
    ref TEXT NOT NULL UNIQUE,
    ts DOUBLE PRECISION NOT NULL,
    plan TEXT NOT NULL, amount_usd DOUBLE PRECISION NOT NULL,
    provider TEXT, status TEXT NOT NULL DEFAULT 'pending',
    paid_at DOUBLE PRECISION, note TEXT, meta TEXT, pay_link TEXT
);
CREATE INDEX IF NOT EXISTS ix_orders_owner ON orders(owner_id);
CREATE TABLE IF NOT EXISTS login_failures (
    ip_hash TEXT NOT NULL, ts DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_login_failures_ip_ts ON login_failures(ip_hash, ts);

-- Upgrade the initial schema without leaving destructive owner cascades behind.
DO $$
DECLARE owned_table TEXT;
BEGIN
    FOREACH owned_table IN ARRAY ARRAY['accounts','usage','outreach','orders'] LOOP
        IF EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conrelid=to_regclass(owned_table)
                   AND conname=owned_table || '_owner_id_fkey' AND confdeltype='c') THEN
            EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', owned_table, owned_table || '_owner_id_fkey');
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (owner_id) REFERENCES users(id)',
                           owned_table, owned_table || '_owner_id_fkey');
        END IF;
    END LOOP;
END $$;
