-- Data protection (UK GDPR, EU GDPR, India DPDP). Runs at every start: every statement is safe to re-run.

-- Orders never keep the payer's IP address. Legacy meta may not be valid JSON: anything unreadable that
-- mentions an IP is dropped whole (no code can read it anyway).
DO $$
DECLARE r RECORD; j JSONB;
BEGIN
    FOR r IN SELECT id, meta FROM orders WHERE meta LIKE '%"ip"%' LOOP
        BEGIN
            j := r.meta::jsonb;
        EXCEPTION WHEN others THEN
            j := '{}'::jsonb;
        END;
        UPDATE orders SET meta = (CASE WHEN jsonb_typeof(j) = 'object' THEN j - 'ip' ELSE '{}'::jsonb END)::text
        WHERE id = r.id;
    END LOOP;
END $$;

-- Erasure: the users row stays (other records point at it) but is anonymised and stamped.
ALTER TABLE users ADD COLUMN IF NOT EXISTS erased_at DOUBLE PRECISION;
-- Paid orders keep the billing email as it was when paid; it outlives erasure for the statutory record period only.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS billing_email TEXT;
UPDATE orders o SET billing_email = u.email FROM users u
WHERE u.id = o.owner_id AND o.status = 'paid' AND o.billing_email IS NULL AND u.erased_at IS NULL;

-- Outreach rows are deleted 12 months after their last change (app/retention.py); status and note edits count.
ALTER TABLE outreach ADD COLUMN IF NOT EXISTS updated DOUBLE PRECISION;

-- Accountability for what admins do to other people's accounts. actor_id NULL: operator console or retention.
-- detail holds references (plan, credits, order ref), never passwords, links or tokens.
CREATE TABLE IF NOT EXISTS admin_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts DOUBLE PRECISION NOT NULL,
    actor_id TEXT REFERENCES users(id),
    target_id TEXT REFERENCES users(id),
    action TEXT NOT NULL,
    detail JSONB NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS ix_admin_events_ts ON admin_events(ts);
CREATE INDEX IF NOT EXISTS ix_admin_events_target ON admin_events(target_id);
CREATE INDEX IF NOT EXISTS ix_admin_events_actor ON admin_events(actor_id);

-- No device fingerprint is collected any more, and the free-tier guard reads network hashes from usage only.
UPDATE accounts SET ip_hash = NULL, fp_hash = NULL WHERE ip_hash IS NOT NULL OR fp_hash IS NOT NULL;
UPDATE usage SET fp_hash = NULL WHERE fp_hash IS NOT NULL;
