-- Daily India backup of paid orders (Income-tax Rules 2026 r.46(8)), app/invoices.py. Runs at every start: safe to re-run.
-- One row per attempt. No personal data: the UTC date, outcome, row count and an error summary written by the app
-- (never a key or a provider response). Deleted 2 years after the attempt (app/retention.py).
CREATE TABLE IF NOT EXISTS invoice_backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day DATE NOT NULL,
    ts DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('ok', 'failed')),
    row_count INTEGER NOT NULL DEFAULT 0,
    error TEXT
);
-- At most one successful backup per day, whatever the number of worker replicas.
CREATE UNIQUE INDEX IF NOT EXISTS ux_invoice_backups_ok_day ON invoice_backups(day) WHERE status = 'ok';
CREATE INDEX IF NOT EXISTS ix_invoice_backups_ts ON invoice_backups(ts);
