-- Refer-a-host programme (app/referrals.py). Runs at every start: every statement is safe to re-run.

-- Bonus videos from rewarded invites, on any plan; spent before plan videos or credits (app/plans.py).
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS bonus_videos INTEGER NOT NULL DEFAULT 0 CHECK (bonus_videos >= 0);
-- One stable invite code per account, for the link /r/<code>. A volatile default gives every existing row its own
-- value when the column is added, and every new account one on insert. Erasure sets it to NULL (the link retires).
-- ponytail: 48 random bits; a collision fails one account insert, and the next ensure_account draws again.
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS referral_code TEXT
    DEFAULT substr(md5(random()::text || clock_timestamp()::text), 1, 12);
CREATE UNIQUE INDEX IF NOT EXISTS ux_accounts_referral_code ON accounts(referral_code);
-- A reservation that spent a bonus video gives it back on refund (plans.refund, once per reservation).
ALTER TABLE usage ADD COLUMN IF NOT EXISTS bonus BOOLEAN NOT NULL DEFAULT FALSE;

-- Who invited whom. One inviter per account. reward_reason NULL = waiting for the invited account's first
-- delivered reel; otherwise the decision ('first_reel_delivered' with rewarded_at, or why not). Erasure sets the
-- erased side to NULL. Deleted 2 years after the reward, or 1 year after signup if never rewarded (app/retention.py).
CREATE TABLE IF NOT EXISTS referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id TEXT REFERENCES users(id),
    referee_id TEXT UNIQUE REFERENCES users(id),
    ts DOUBLE PRECISION NOT NULL,
    rewarded_at DOUBLE PRECISION,
    reward_reason TEXT,
    CHECK (referrer_id <> referee_id)
);
CREATE INDEX IF NOT EXISTS ix_referrals_referrer ON referrals(referrer_id, rewarded_at);
